# Generated by Django 4.2.6 on 2023-11-28 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('cust_l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile No. e.g., 254712345678')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1)),
                ('row', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('bay', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('tier', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Stock Keeping Unit')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Stationery', 'Stationery'), ('Furniture', 'Furniture'), ('Jewellery', 'Jewellery'), ('Clothing', 'Clothing'), ('Electronic', 'Electronic')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('product_image', models.ImageField(upload_to='', verbose_name='product_images')),
                ('item_created_at', models.DateTimeField(auto_now_add=True)),
                ('item_updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_location', to='landing_page.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('item_name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('sup_l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='Email Address')),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile No. e.g., 254712345678')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_transferred', models.PositiveIntegerField()),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='landing_page.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.product')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='landing_page.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('order_updated_at', models.DateTimeField(auto_now=True)),
                ('total_items', models.PositiveIntegerField(verbose_name='Total Items')),
                ('order_type', models.CharField(blank=True, choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], verbose_name='Order Type')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('GIT', 'GIT'), ('Completed', 'Completed')], verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='landing_page.product')),
            ],
        ),
    ]
