# Generated by Django 4.2.6 on 2023-10-30 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('cust_l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('mobile_no', models.PositiveIntegerField(blank=True, max_length=12, null=True, verbose_name='Mobile No. e.g., 254712345678')),
                ('address', models.TextField(blank=True, verbose_name='Home Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('sup_l_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email Address')),
                ('mobile_no', models.PositiveIntegerField(blank=True, max_length=12, verbose_name='Mobile No. e.g., 254712345678')),
                ('address', models.TextField(blank=True, verbose_name='Home Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='Stock Keeping Unit')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Stationery', 'Stationery'), ('Furniture', 'Furniture'), ('Jewellery', 'Jewellery'), ('Clothing', 'Clothing'), ('Electronic', 'Electronic')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100, verbose_name='Location (e.g., Aisle/Shelf/Bin)')),
                ('product_image', models.ImageField(upload_to='', verbose_name='product_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, verbose_name='Order ID')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('order_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], verbose_name='Order Type')),
                ('total_items', models.PositiveIntegerField(verbose_name='Total Items')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
