# Generated by Django 4.2.6 on 2023-11-08 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 8, 7, 39, 11, 680193, tzinfo=datetime.timezone.utc)),
        ),
    ]
