# Generated by Django 4.2.6 on 2023-12-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Purchase Orders', 'Purchase Orders'), ('Sales Orders', 'Sales Orders')], verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_location', to='landing_page.location', verbose_name=' Available Locations(Zone, Row, Bay, Tier)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='product_images'),
        ),
    ]
