# Generated by Django 4.2.6 on 2023-10-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_f_name', models.CharField(max_length=100)),
                ('cust_l_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_f_name', models.CharField(max_length=100)),
                ('sup_l_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Stationery', 'Stationery'), ('Furniture', 'Furniture'), ('Jewellery', 'Jewellery'), ('Clothing', 'Clothing'), ('Electronic', 'Electronic')], max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, verbose_name='Order ID')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('order_type', models.CharField(choices=[('inbound', 'Inbound'), ('Outbound', 'Outbound')], verbose_name='Order Type')),
                ('total_items', models.IntegerField(verbose_name='Total Items')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
