# Generated by Django 4.2.6 on 2023-12-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_order_order_type_alter_product_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='No-image-found.jpg', upload_to='', verbose_name='product_images'),
        ),
    ]
