# Generated by Django 4.2.6 on 2023-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_alter_product_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobile_no',
            field=models.PositiveIntegerField(blank=True, max_length=12, null=True, verbose_name='Mobile No. e.g., 254712345678'),
        ),
    ]
