# Generated by Django 4.2.6 on 2024-01-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_product_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransfers',
            name='source_location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='landing_page.location'),
        ),
    ]
