# Generated by Django 4.2.6 on 2023-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_alter_order_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
