# Generated by Django 4.2.6 on 2023-11-14 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing_page', '0011_rename_trans_to_transfers_transfer_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_transferred', models.PositiveIntegerField()),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='landing_page.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.product')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='landing_page.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transfers',
        ),
    ]
