# Generated by Django 4.2.6 on 2023-11-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0013_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default=[('Bin 1', 'Bin 1'), ('Bin 2', 'Bin 2'), ('Bin 3', 'Bin 3'), ('Bin 4', 'Bin 4'), ('Bin 5', 'Bin 5'), ('Bin 6', 'Bin 6')], max_length=100),
        ),
    ]
