# Generated by Django 4.2.6 on 2023-11-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0015_alter_location_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('item_name', 'location')},
        ),
    ]
