# Generated by Django 4.2.6 on 2023-11-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0017_alter_customer_email_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('GIT', 'GIT'), ('Completed', 'Completed')], verbose_name='Status'),
        ),
    ]
